In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/tutorial/splits/split.parquet")

In [3]:
df

,system_id,uniqueness,split,cluster,cluster_for_val_split,system_pass_validation_criteria,system_pass_statistics_criteria,system_proper_num_ligand_chains,system_proper_pocket_num_residues,system_proper_num_interactions,system_proper_ligand_max_molecular_weight,system_has_binding_affinity,system_has_apo_or_pred
0,101m__1__1.A__1.C_1.D,101m__A__C_D_c188899,train,c14,c0,True,True,1,27,20,616.177293,False,False
1,102m__1__1.A__1.C,102m__A__C_c237197,train,c14,c0,True,True,1,26,20,616.177293,False,True
2,103m__1__1.A__1.C_1.D,103m__A__C_D_c252759,train,c14,c0,False,True,1,26,16,616.177293,False,False
3,104m__1__1.A__1.C_1.D,104m__A__C_D_c274687,train,c14,c0,False,True,1,27,21,616.177293,False,False
4,105m__1__1.A__1.C_1.D,105m__A__C_D_c221688,train,c14,c0,False,True,1,28,20,616.177293,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
409721,9xia__1__2.A_4.A__4.B_4.D,9xia__A_A__B_D_c20731,train,c256,c126,False,False,1,23,6,178.084124,False,False
409722,9xim__1__1.A_1.B__1.E_1.F_1.G,9xim__A_B__E_F_G_c240203,train,c256,c126,False,False,1,21,6,150.052823,False,False
409723,9xim__1__1.A_1.B__1.H_1.I_1.J,9xim__A_B__H_I_J_c313183,train,c256,c126,False,False,1,19,5,150.052823,False,False
409724,9xim__1__1.C_1.D__1.K_1.L_1.M,9xim__C_D__K_L_M_c215891,train,c256,c126,False,False,1,20,3,150.052823,False,False
409725,9xim__1__1.C_1.D__1.N_1.O_1.P,9xim__C_D__N_O_P_c219610,train,c256,c126,False,False,1,20,6,150.052823,False,False

In [4]:
train_df = df[df["split"] == "train"]

In [5]:
len(train_df)

309140

In [8]:
df['cluster_for_val_split'] == df['cluster']

0         False
1         False
2         False
3         False
4         False
          ...
409721    False
409722    False
409723    False
409724    False
409725    False
Length: 408695, dtype: bool

In [9]:
cluster_df =pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/tutorial/clusters/cluster=communities/directed=False/metric=protein_seqsim_max/threshold=70/data.parquet")

In [10]:
cluster_df

,system_id,label,metric,cluster,directed,threshold
0,7kne__1__1.A__1.E,c0,protein_seqsim_max,communities,False,70
1,8dlo__1__1.B__1.J,c0,protein_seqsim_max,communities,False,70
2,8tyo__1__1.A__1.L,c0,protein_seqsim_max,communities,False,70
3,7y42__1__1.B__1.S,c0,protein_seqsim_max,communities,False,70
4,7xdl__1__1.B__1.IA,c0,protein_seqsim_max,communities,False,70
...,...,...,...,...,...,...
479806,3bib__1__1.A__1.B_1.C,c13542,protein_seqsim_max,communities,False,70
479807,3wec__1__1.A__1.B_1.C,c13543,protein_seqsim_max,communities,False,70
479808,7urg__1__1.A_1.B__1.D,c13544,protein_seqsim_max,communities,False,70
479809,7xpg__1__39.B_40.C_59.B__40.F_59.E,c13545,protein_seqsim_max,communities,False,70
479810,7sqc__1__1.O_1.P__1.VO,c13546,protein_seqsim_max,communities,False,70

### v2

In [11]:
v2_train_test_parquet = pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/v2/splits/stratification/train_vs_test_data/max_similarities__test_vs_train__protein_seqsim_weighted_sum.parquet")

In [12]:
v2_train_test_parquet

,system_id,train_system_id,protein_seqsim_weighted_sum
0,1q16__1__1.B_1.C__1.N,1kqf__1__1.B_1.C__1.L,29
1,1siw__1__1.B_1.C__1.L,1kqf__1__1.B_1.C__1.L,29
2,1uhe__1__2.A_2.B_4.A_4.B__4.C,4cs0__1__1.A_1.B__1.D_1.E,28
3,1z82__1__1.A_1.B__1.C_1.J,1o5i__1__1.B__1.E,29
4,1z82__1__1.A_1.B__1.D_1.I,1o5i__1__1.B__1.E,29
...,...,...,...
60,7s2r__1__1.A__1.C,7u7n__1__1.B_1.C__1.H,22
61,7vzn__1__1.A_1.B__1.S_1.T_1.U,6n9a__1__1.B_1.C__1.I_1.J,29
62,7z5u__1__1.A__1.B_1.C,3mdb__1__1.A_1.C__1.I,24
63,7zbv__1__1.A__1.B_1.E,3mdb__1__1.A_1.C__1.I,24
64,8gmi__1__1.B__1.K,6hxj__1__1.D_1.E__1.R,25

In [15]:
test_parquet = pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/v2/splits/stratification/train_vs_test_data/test_set.parquet")

In [16]:
test_parquet

,system_id,pli_unique_qcov,protein_seqsim_weighted_sum,protein_fident_weighted_sum,protein_lddt_weighted_sum,pocket_fident_qcov,pocket_lddt_qcov,pocket_lddt,pocket_qcov,tanimoto_similarity_max,passes_quality,novel_pocket_pli,novel_ligand_pli,novel_protein,novel_ligand,novel_all,not_novel
0,1z82__1__1.A_1.B__1.C_1.J,18.0,29.0,21.0,0.0,0.0,0.0,0.0,17.0,100.000000,True,True,False,True,False,False,False
1,2cvc__1__1.A__1.L,5.0,20.0,0.0,0.0,0.0,0.0,0.0,9.0,100.000000,True,True,False,True,False,False,False
2,5h47__10__1.J__1.PB,17.0,24.0,0.0,37.0,23.0,33.0,50.0,38.0,60.714286,True,True,False,True,False,False,False
3,6b2a__1__1.A_1.B_1.C__1.I_1.L,10.0,23.0,22.0,23.0,21.0,24.0,28.0,26.0,100.000000,True,True,False,True,False,False,False
4,6wk9__2__1.E_1.F_1.G__1.Q_1.R_1.U_1.V,0.0,26.0,24.0,24.0,0.0,0.0,24.0,16.0,100.000000,True,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031,8tjc__1__1.B__1.N,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.824561,True,True,True,True,True,True,False
1032,8ttj__4__1.D__1.CA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.428571,True,True,False,True,False,False,False
1033,8uuf__1__1.A__1.B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.210526,True,True,False,True,False,False,False
1034,8w6p__1__1.A_1.B__1.E,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.000000,True,True,False,True,False,False,False
1035,8wsm__1__1.A__1.D,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.789474,True,True,False,True,False,False,False

In [18]:
total_parquet = pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/v2/splits/split.parquet")

In [19]:
total_parquet

,system_id,uniqueness,split,cluster,cluster_for_val_split,system_pass_validation_criteria,system_pass_statistics_criteria,system_proper_num_ligand_chains,system_proper_pocket_num_residues,system_proper_num_interactions,system_proper_ligand_max_molecular_weight,system_has_binding_affinity,system_has_apo_or_pred
0,101m__1__1.A__1.C_1.D,101m__A__C_D_c188899,train,c14,c0,True,True,1,27,20,616.177293,False,False
1,102m__1__1.A__1.C,102m__A__C_c237197,train,c14,c0,True,True,1,26,20,616.177293,False,True
2,103m__1__1.A__1.C_1.D,103m__A__C_D_c252759,train,c14,c0,False,True,1,26,16,616.177293,False,False
3,104m__1__1.A__1.C_1.D,104m__A__C_D_c274687,train,c14,c0,False,True,1,27,21,616.177293,False,False
4,105m__1__1.A__1.C_1.D,105m__A__C_D_c221688,train,c14,c0,False,True,1,28,20,616.177293,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
409721,9xia__1__2.A_4.A__4.B_4.D,9xia__A_A__B_D_c20731,train,c256,c126,False,False,1,23,6,178.084124,False,False
409722,9xim__1__1.A_1.B__1.E_1.F_1.G,9xim__A_B__E_F_G_c240203,train,c256,c126,False,False,1,21,6,150.052823,False,False
409723,9xim__1__1.A_1.B__1.H_1.I_1.J,9xim__A_B__H_I_J_c313183,train,c256,c126,False,False,1,19,5,150.052823,False,False
409724,9xim__1__1.C_1.D__1.K_1.L_1.M,9xim__C_D__K_L_M_c215891,train,c256,c126,False,False,1,20,3,150.052823,False,False
409725,9xim__1__1.C_1.D__1.N_1.O_1.P,9xim__C_D__N_O_P_c219610,train,c256,c126,False,False,1,20,6,150.052823,False,False

In [20]:
total_parquet['system_proper_num_ligand_chains'].unique()

array([1, 2, 4, 3, 5])

In [1]:
import pandas as pd

In [2]:
data = pd.read_parquet("/home/possu/jinho/datasets/plinder/2024-06/v2/clusters/cluster=communities/directed=False/metric=protein_seqsim_max/threshold=70/data.parquet")

In [3]:
data

,system_id,label,metric,cluster,directed,threshold
0,7kne__1__1.A__1.E,c0,protein_seqsim_max,communities,False,70
1,8dlo__1__1.B__1.J,c0,protein_seqsim_max,communities,False,70
2,8tyo__1__1.A__1.L,c0,protein_seqsim_max,communities,False,70
3,7y42__1__1.B__1.S,c0,protein_seqsim_max,communities,False,70
4,7xdl__1__1.B__1.IA,c0,protein_seqsim_max,communities,False,70
...,...,...,...,...,...,...
479806,3bib__1__1.A__1.B_1.C,c13542,protein_seqsim_max,communities,False,70
479807,3wec__1__1.A__1.B_1.C,c13543,protein_seqsim_max,communities,False,70
479808,7urg__1__1.A_1.B__1.D,c13544,protein_seqsim_max,communities,False,70
479809,7xpg__1__39.B_40.C_59.B__40.F_59.E,c13545,protein_seqsim_max,communities,False,70
479810,7sqc__1__1.O_1.P__1.VO,c13546,protein_seqsim_max,communities,False,70

In [ ]:
linked = pd.read_parquet('/home/possu/jinho/datasets/plinder/2024-06/v2/links/kind=pred/links.parquet')

In [5]:
linked

,reference_system_id,id,pocket_fident,pocket_lddt,protein_fident_qcov_weighted_sum,protein_fident_weighted_sum,protein_lddt_weighted_sum,target_id,sort_score,receptor_file,...,posebusters_most_extreme_ligand_element_waters,posebusters_most_extreme_protein_element_waters,posebusters_most_extreme_ligand_vdw_waters,posebusters_most_extreme_protein_vdw_waters,posebusters_most_extreme_sum_radii_waters,posebusters_most_extreme_distance_waters,posebusters_most_extreme_sum_radii_scaled_waters,posebusters_most_extreme_relative_distance_waters,posebusters_most_extreme_clash_waters,kind
0,5f5x__1__1.A__1.C,Q734X3_A,96.0,100.0,99.0,99.0,100.0,Q734X3,98.77,/plinder/2024-06/assignments/pred/5f5x__1__1.A...,...,O,O,1.55,1.55,3.10,2.711297,3.10,0.874612,0.0,pred
1,5f5x__3__1.B__1.D,Q734X3_A,96.0,100.0,99.0,99.0,100.0,Q734X3,98.77,/plinder/2024-06/assignments/pred/5f5x__3__1.B...,...,O,O,1.55,1.55,3.10,2.467863,3.10,0.796085,0.0,pred
2,5f5x__1__1.B__1.D,Q734X3_A,96.0,100.0,99.0,99.0,100.0,Q734X3,98.77,/plinder/2024-06/assignments/pred/5f5x__1__1.B...,...,O,O,1.55,1.55,3.10,2.467863,3.10,0.796085,0.0,pred
3,5jyb__1__1.A__1.G,Q734X3_A,95.0,100.0,99.0,99.0,100.0,Q734X3,98.77,/plinder/2024-06/assignments/pred/5jyb__1__1.A...,...,C,O,1.70,1.55,3.25,2.776398,3.25,0.854276,0.0,pred
4,5f5x__2__1.A__1.C,Q734X3_A,96.0,100.0,99.0,99.0,100.0,Q734X3,98.77,/plinder/2024-06/assignments/pred/5f5x__2__1.A...,...,O,O,1.55,1.55,3.10,2.711297,3.10,0.874612,0.0,pred
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163811,6x3q__1__1.A__1.B,A8AWU7_A,100.0,79.0,99.0,99.0,88.0,A8AWU7,38.90,/plinder/2024-06/assignments/pred/6x3q__1__1.A...,...,O,O,1.55,1.55,3.10,2.679286,3.10,0.864286,0.0,pred
163812,8st5__1__1.A__1.B,A8AWU7_A,100.0,95.0,99.0,99.0,88.0,A8AWU7,38.90,/plinder/2024-06/assignments/pred/8st5__1__1.A...,...,O,O,1.55,1.55,3.10,2.943679,3.10,0.949574,0.0,pred
163813,6efd__1__1.A__1.B,A8AWU7_A,100.0,81.0,99.0,99.0,87.0,A8AWU7,38.90,/plinder/2024-06/assignments/pred/6efd__1__1.A...,...,O,O,1.55,1.55,3.10,2.715962,3.10,0.876117,0.0,pred
163814,8st6__1__1.A__1.D,A8AWU7_A,100.0,80.0,99.0,99.0,88.0,A8AWU7,38.90,/plinder/2024-06/assignments/pred/8st6__1__1.A...,...,O,O,1.55,1.55,3.10,2.533843,3.10,0.817369,0.0,pred
163815,3rgu__3__1.C__1.E,A1C3L3_A,100.0,94.0,99.0,100.0,91.0,A1C3L3,37.07,/plinder/2024-06/assignments/pred/3rgu__3__1.C...,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pred